Huge improvement
1) implemented getitctl status
2) implemented getitctl cleanup-queue to cleanup fully retrieved urls
   from queue file and add those to completed file
3) now checks progress every 30 seconds and moves fully retrieved urls
   to completed.txt file

diff --git a/getitd b/getitd
--- a/getitd
+++ b/getitd
@@ -13,17 +13,17 @@ CONFIG="${HOME}/.getitrc"
 PIDS_FILE="/tmp/getit.pids"
 LOG_FILES_PREFIX="/tmp/getit.log"
 
-# Default configs
+# default configs
 DOWNLOAD_DIR="${HOME}/downloads"
 QUEUE="${DOWNLOAD_DIR}/queue.txt"
 LIMIT_RATE=0
 TRIES=20
 WAIT_RETRY=30
 
-# Read getitrc file if it is present
+# read getitrc file if it is present
 [ -r $CONFIG ] && . $CONFIG
 
-# Create download directory if it is not exists
+# create download directory if it is not exists
 if [ "x`ls ${DOWNLOAD_DIR} 2>/dev/null`" == "x" ] ; then
     mkdir -p $DOWNLOAD_DIR
 
@@ -33,7 +33,7 @@ if [ "x`ls ${DOWNLOAD_DIR} 2>/dev/null`" == "x" ] ; then
     fi
 fi
 
-# Cleanup function
+# cleanup function
 function clean_up {
 
     if [ -f $PIDS_FILE ] ; then
@@ -46,30 +46,21 @@ function clean_up {
         done
     fi
 
-    # Remove log files and pids file
+    # remove log files and pids file
     rm -rf $PIDS_FILE
     rm -rf $LOG_FILES_PREFIX.*
 }
 
-function terminate {
-    clean_up
-    kill $SLAVE
-    exit
-}
+function start_download {
 
-# Do the cleanup when one of SIGHUP, SIGINT, SIGTERM signals is received
-trap terminate SIGHUP SIGINT SIGTERM
-
-while (true);
-do
     if [ -f $QUEUE ] ; then
 
         cat $QUEUE | while read row;
         do
-            # Ignore lines that have ; or # at the beginning
+            # ignore lines that have ; or # at the beginning
             row=`echo $row | sed -e 's/^\s*[;#].*//'`
 
-            # Extract url, download_dir and limit_rate
+            # extract url, download_dir and limit_rate
             url=`echo $row | awk '{print $1}'`
             download_dir="${DOWNLOAD_DIR}/`echo $row | awk '{print $2}'`"
             limit_rate=`echo $row | awk '{print $3}'`
@@ -84,6 +75,8 @@ do
                     limit_rate=$LIMIT_RATE;
                 fi
 
+                # prevent starting wget when other process is downloading same url, this is happening when there are
+                # duplicated lines in queue file
                 if [ "x`ps aux | grep wget | grep -v grep | awk '{ print $NF }' | grep $url`" == "x" ] ; then
 
                     cd $download_dir
@@ -93,23 +86,38 @@ do
                          $url 1>/dev/null &
                     pid=$!
 
-                    # Save pid somewhere so we can cleanup it later if needed
+                    # save pid somewhere so we can cleanup it later
                     echo $pid >> $PIDS_FILE
                 fi
             fi
 
         done
-
-        # wait for changes
-        inotifywait --quiet --event MOVE_SELF --event MODIFY $QUEUE 1>/dev/null &
-        SLAVE=$!
-        wait $SLAVE
-
-        # Queue file has been modified so cleanup running process and then try again
-        clean_up
-    else
-        echo "Nothing to do. You have to create your ~/.getitrc file and specify DOWNLOAD_DIR, QUEUE and LIMIT_RATE there."
-        clean_up
-        exit;
     fi
+}
+
+function terminate {
+    clean_up
+    kill $inotify_pid
+    exit
+}
+
+# Do the cleanup when one of SIGHUP, SIGINT, SIGTERM signals is received
+trap terminate SIGHUP SIGINT SIGTERM
+
+while (true);
+do
+    # 2 indicates timeout
+    if [ "$inotify_ret" != "2" ] ; then
+        clean_up
+        start_download
+    else
+        # run cleanup-queue in the background and quickly watch queue file again
+        getitctl cleanup-queue &
+    fi
+
+    # watch queue file
+    inotifywait --quiet --timeout=30 --event MOVE_SELF --event MODIFY $QUEUE 1>/dev/null &
+    inotify_pid=$!      # catch its pid so we can cleanup it later when a SIGNAL received
+    wait $inotify_pid   # wait for it
+    inotify_ret=$?      # an then catch the return value, 2 indicates timeout
 done
